import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/auth";
import { generateCertificatePdf } from '@/lib/pdf';
import { sendCertificateEmail } from '@/lib/email';
import { randomUUID } from 'node:crypto';
import { requireRole } from "@/lib/auth";
import { isString } from "@/lib/validation";
import { submissionInclude } from "@/lib/queries";
import { audit } from "@/lib/audit";
import { notify } from "@/lib/notifications";
import { deliverCertificates, issueCertificatesForSubmission } from "@/lib/issue-certificates";

type CertificateSubmission = {
  projectId: string;
  teamName: string;
  student?: { email: string; name: string } | null;
  project: { title: string };
};
type Params = { params: Promise<{ id: string }> };

async function createCertificateIfMissing(submission: CertificateSubmission, companyId: string) {
  // Avoid duplicate certificates for same submission/student
  const studentEmail = submission.student?.email || `${submission.teamName}@example.com`;
  const exists = await prisma.certificate.findFirst({
    where: {
      projectId: submission.projectId,
      studentEmail,
    },
  });
  if (exists) return exists;
/**
 * PATCH /api/submissions/[id] — project owner reviews a submission.
 * - APPROVED: one-step approval; certificates are issued to every accepted team
 *   member in the same transaction (FR-C8, FR-V1).
 * - REJECTED: feedback is required; the team may resubmit.
 */
export async function PATCH(req: Request, { params }: Params) {
  const auth = await requireRole("CLIENT");
  if (auth instanceof NextResponse) return auth;

  const issueDate = new Date().toISOString().split("T")[0];
  const expiryDate = new Date(new Date().setFullYear(new Date().getFullYear() + 2))
    .toISOString()
    .split("T")[0];

  const cert = await prisma.certificate.create({
    data: {
      certId: `CERT-${randomUUID()}`,
      title: `Accredited Certification in ${submission.project.title}`,
      studentName: submission.student?.name || submission.teamName,
      studentEmail,
      issueDate,
      expiryDate,
      status: "Verified",
      companyId,
      projectId: submission.projectId,
    },
  });

  // Attempt to generate PDF and email it to the student. Failures here should not break the main flow.
  try {
    const company = await prisma.user.findUnique({ where: { id: companyId } });
    const companyName = company?.name;

    const pdfBuffer = await generateCertificatePdf({
      certId: cert.certId,
      title: cert.title,
      studentName: cert.studentName,
      studentEmail: cert.studentEmail,
      issueDate: cert.issueDate,
      expiryDate: cert.expiryDate,
      companyName,
    });

    await sendCertificateEmail({
      to: cert.studentEmail,
      subject: `Your Certificate - ${cert.title}`,
      text: `Congratulations ${cert.studentName}! Attached is your certificate generated by CertiTask.`,
      attachment: { filename: `${cert.certId}.pdf`, content: pdfBuffer },
    });
  } catch (err) {
    console.error('Failed to generate or send certificate PDF:', err);
  }

  return cert;
}
export async function PATCH(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await getSession();
  if (!session || (session.role !== "COMPANY" && session.role !== "STUDENT")) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const { id } = await params;
    const payload = await req.json();
    const { status, feedback } = payload;
    const { status, feedback } = await req.json();

    if (!['CompanyApproved', 'Rejected', 'StudentConfirmed'].includes(status)) {
      return NextResponse.json({ error: "Status is required" }, { status: 400 });
    if (status !== "APPROVED" && status !== "REJECTED") {
      return NextResponse.json({ error: "Status must be APPROVED or REJECTED" }, { status: 400 });
    }
    if (status === "REJECTED" && !isString(feedback, 5000)) {
      return NextResponse.json({ error: "Tell the team what needs to change" }, { status: 400 });
    }
    if (feedback !== undefined && feedback !== null && feedback !== "" && !isString(feedback, 5000)) {
      return NextResponse.json({ error: "Feedback is too long" }, { status: 400 });
    }

    // Load submission (company must own the project for company actions)
    const submission = await prisma.submission.findUnique({
      where: { id },
      include: { project: true, student: true },
      include: { project: { select: { clientId: true } } },
    });

    if (!submission) {
    if (!submission || submission.project.clientId !== auth.userId) {
      return NextResponse.json({ error: "Submission not found" }, { status: 404 });
    }
    if (submission.status === "APPROVED") {
      return NextResponse.json({ error: "This submission is already approved" }, { status: 409 });
    }

    // COMPANY actions
    if (session.role === "COMPANY") {
      if (submission.project.companyId !== session.userId) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
      }

      if (status === "StudentConfirmed") {
        return NextResponse.json({ error: "Invalid company action" }, { status: 400 });
      }

      // Company confirms deliverable
      if (status === "CompanyApproved") {
        // If student already confirmed, issue certificate and set final status to Approved
        if (submission.status === "StudentConfirmed") {
          const cert = await createCertificateIfMissing(submission, session.userId);
          const updated = await prisma.submission.update({
            where: { id },
            data: { status: "Approved", feedback },
          });
          return NextResponse.json({ success: true, submission: updated, certificate: cert });
        } else {
          // Mark as company-approved and wait for student confirmation
          const updated = await prisma.submission.update({
            where: { id },
            data: { status: "CompanyApproved", feedback },
          });
          return NextResponse.json({ success: true, submission: updated });
        }
      }

      // Company rejects
      if (status === "Rejected") {
        const updated = await prisma.submission.update({
          where: { id },
          data: { status: "Rejected", feedback },
        });
        return NextResponse.json({ success: true, submission: updated });
      }

      // Other status updates by company
      const updated = await prisma.submission.update({
    const { updated, result } = await prisma.$transaction(async (tx) => {
      const updated = await tx.submission.update({
        where: { id },
        data: { status, ...(feedback && { feedback }) },
        data: {
          status,
          feedback: feedback ? String(feedback).trim() : null,
          reviewedAt: new Date(),
        },
        include: submissionInclude,
      });
      return NextResponse.json({ success: true, submission: updated });
    }
      await audit(auth, status === "APPROVED" ? "submission.approved" : "submission.rejected", "submission", id, { from: submission.status }, tx);

    // STUDENT actions
    if (session.role === "STUDENT") {
      // Only the submitting student/team may confirm
      if (submission.studentId !== session.userId) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
      }

      if (status === "StudentConfirmed") {
        // Student confirmation is only a handoff step; certificate issuance must remain company-only.
        if (submission.status === "CompanyApproved") {
          const updated = await prisma.submission.update({
            where: { id },
            data: { status: "Approved" },
          });
          return NextResponse.json({ success: true, submission: updated });
      const result = status === "APPROVED"
        ? await issueCertificatesForSubmission(tx, auth, id)
        : { issued: [] as string[], held: [] as string[] };
      if (status === "REJECTED") {
        for (const m of updated.team.members.filter((x) => x.status === "ACCEPTED")) {
          await notify(m.user.id, "submission.reviewed", "Changes requested", `${updated.project.title}: the client asked for changes. See their feedback and resubmit.`, "/talent/dashboard?tab=submissions", tx);
        }

        const updated = await prisma.submission.update({
          where: { id },
          data: { status: "StudentConfirmed" },
        });
        return NextResponse.json({ success: true, submission: updated });
      }
      return { updated, result };
    }, { maxWait: 10_000, timeout: 60_000 }); // remote DB: several sequential round trips

      // Student cannot perform other status changes
      return NextResponse.json({ error: "Invalid action" }, { status: 400 });
    }
    // Email delivery happens after commit and never blocks the response.
    if (result.issued.length > 0) void deliverCertificates(result.issued);

    return NextResponse.json({ error: "Unhandled role" }, { status: 400 });
    return NextResponse.json({ success: true, submission: updated, certificatesIssued: result.issued.length, certificatesHeld: result.held.length });
  } catch (error) {
    console.error("Update submission status error:", error);
    return NextResponse.json({ error: "Failed to update submission status" }, { status: 500 });
    console.error("Review submission error:", error);
    return NextResponse.json({ error: "Failed to review submission" }, { status: 500 });
  }
}
